spring.application.name=BlossemBackend
# MongoDB Connection (Using your provided string)
spring.data.mongodb.uri=mongodb+srv://rivishkaps2025_db_user:PTipgsyfg2BJbZvD@salondb.aaywcoi.mongodb.net/SalonDb?appName=SalonDb

# Server Port
server.port=8081
