spring.application.name=SalonBackend
server.port=8081
# server.address=0.0.0.0 # Standard localhost should be fine for most cases

spring.data.mongodb.uri=mongodb+srv://rivishkaps2025_db_user:PTipgsyfg2BJbZvD@salondb.aaywcoi.mongodb.net/SalonDb
logging.level.org.springframework=INFO
