server.port=8081

spring.data.mongodb.uri=mongodb+srv://rivishkaps2025_db_user:PTipgsyfg2BJbZvD@salondb.aaywcoi.mongodb.net/SalonDb
spring.data.mongodb.database=SalonDb

spring.main.allow-circular-references=true

jwt.secret=MyVerySecretKey123456
jwt.expiration=86400000
